const mockUser =  {
  "login": "neet1313",
  "id": 47270603,
  "node_id": "MDQ6VXNlcjQ3MjcwNjAz",
  "avatar_url": "https://avatars.githubusercontent.com/u/47270603?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/neet1313",
  "html_url": "https://github.com/neet1313",
  "followers_url": "https://api.github.com/users/neet1313/followers",
  "following_url": "https://api.github.com/users/neet1313/following{/other_user}",
  "gists_url": "https://api.github.com/users/neet1313/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/neet1313/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/neet1313/subscriptions",
  "organizations_url": "https://api.github.com/users/neet1313/orgs",
  "repos_url": "https://api.github.com/users/neet1313/repos",
  "events_url": "https://api.github.com/users/neet1313/events{/privacy}",
  "received_events_url": "https://api.github.com/users/neet1313/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Prabhneet Singh",
  "company": "ACME DRINKTEC SOLUTIONS LLP",
  "blog": "",
  "location": "New Delhi",
  "email": null,
  "hireable": true,
  "bio": "Hi there! 👋",
  "twitter_username": "PrabhneetS1ngh",
  "public_repos": 35,
  "public_gists": 1,
  "followers": 0,
  "following": 1,
  "created_at": "2019-02-02T09:44:55Z",
  "updated_at": "2022-12-21T20:45:06Z"
};

export default mockUser;